apiVersion: 1

policies:
  - orgId: 1
    receiver: Recruitment Platform Email
    group_by: [grafana_folder, alertname]
    routes:
      - receiver: Recruitment Platform Email
        object_matchers:
          - [service, '=', recruitment-platform]
